name: architecture_template_v2
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #Core Dependencies
  kartal: ^3.5.0
  vexana: ^3.5.4
  equatable: ^2.0.5
  flutter_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  envied: ^0.5.2
# dependency_overrides:
widgets:
  path: module/widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter_gen:
  output: lib/product/generated/
  integrations:
     lottie: true

flutter:
 
  uses-material-design: true

  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  