name: architecture_template_v2
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Core
  equatable: ^2.0.5
  get_it: ^7.6.4

  #Network Dependencies
  vexana: ^3.5.4

  #State
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.4.9

  #Config
  easy_localization: ^3.0.3
  
  #Utility 
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  kartal: ^3.5.0
  google_fonts: ^6.1.0

  #Navigation
  auto_route: ^7.8.4

# dependency_overrides:
# Modules
  core:
     path: module/core
  widgets:
     path: module/widgets
  gen:
    path: module/gen
  common: 
    path: module/common

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  device_preview: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  
  assets:
     - asset/translations/
  #   - images/a_dot_ham.jpeg

  